### ISSUE TITLE
FEATURE: Allow Alternate Authentication Storage Options

### ISSUE THREAD

**Issue by jamesdurrant** [bullhorn/taurus#1]
Currently, Taurus uses [Cache.ts](https://github.com/bullhorn/taurus/blob/c54f469a1eeb53a387055fb2f84a5a2d36d128b1/src/utils/Cache.ts) to store the `BhRestToken`, etc. `Cache.ts` uses HTML5 Storage (`window.localstorage`), which is not available on NodeJS, and therefore prevents Taurus from being used for API User authentication.

Could you please consider providing alternative options to override authentication storage, such as using a database to store variables set by Taurus?

Cheers

**Comment by bvkimball** [comment]
Cache should fallback to just using InMemory storage if localStorage is unavailable, I will double check this.  If you want to use an alternate strategy you can override the storage method in the Cache class.

see https://github.com/bullhorn/taurus/blob/master/src/utils/Cache.ts#L25

I will look into providing some default alternatives.

**Comment by bvkimball** [comment]
Closed by #16
