### ISSUE TITLE
Add Event Subscription Service

### ISSUE THREAD

**Issue by bvkimball** [bullhorn/taurus#4]
/event
Lets you subscribe and unsubscribe to event types and get entity events, field map change events, and job match search events.

Subscribe
HTTP Method

PUT

URL Specification

[corporation-token]/event/subscription/[subscription ID]

URL Parameters

 

Required

 

type

entity | fieldMapChange | jobMatchSearch

names

Required with "entity" type. A comma-separated list of entity names.

eventTypes

Required with "entity" type. A comma-separated list of entity event types: INSERTED, UPDATED, DELETED

Optional

 

BhRestToken

Token that represents a session established by the login process. Must be sent with all subsequent requests to the API. The session key can be provided in the BhRestToken query string, a cookie, or a special HTTP header. See Session Key for details on how to provide it.

Examples

 

Sample URL

https://rest.bullhorn.com/e999/event/subscription/abcde?type=entity&names=Candidate&eventTypes=INSERTED,UPDATED,DELETED

Sample Response

{'lastRequestId': 0,
 'subscriptionId': 'abcde',
 'createdOn': 1335285871323,
 'jmsSelector': "JMSType='ENTITY' AND BhCorpId=44 AND BhEntityName='Candidate' AND BhEntityEventType IN ('UPDATED','INSERTED','DELETED')"}
Get Events
HTTP Method

GET

URL Specification

[corporation-token]/event/subscription/[subscription ID]

URL Parameters

 

Required

 

maxEvents

Integer specifying the maximum number of events to be returned.

Optional

 

BhRestToken

Token that represents a session established by the login process. Must be sent with all subsequent requests to the API. The session key can be provided in the BhRestToken query string, a cookie, or a special HTTP header. See Session Key for details on how to provide it.

Examples

 

Sample URL

https://rest.bullhorn.com/e999/event/subscription/abcde?maxEvents=100

Sample Response

{'requestId': 1,
 'events': [{'eventId': 'ID:JBM-40004219',
             'eventType': 'ENTITY',
             'entityName': 'Candidate',
             'eventMetadata': {},
             'updatedProperties': ['phone'],
             'entityEventType': 'UPDATED',
             'eventTimestamp': 1335286112652,
             'entityId': 123}]}

**Comment by michael-amaya-bh** [comment]
Closing as we are not looking at adding any enhancements at this time.
